import Head from "next/head";
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profile from "../public/profile.jpeg";
import mavs from "../public/mavs.png";
import portfolio from "../public/portfolio.png";
import empire from "../public/empire.png";
import Image from "next/image";
import mav1 from "../public/mav1.png";
import mav2 from "../public/mav2.png";
import emp1 from "../public/emp1.png";
import emp2 from "../public/emp2.png";
import per1 from "../public/per1.png";
import dietyou from "../public/dietyou.png";
import diet1 from "../public/diet1.png";
import diet2 from "../public/diet2.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Vindiya&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Vindiya Wickramathunga</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Vindiya Wickramathunga
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineering Undergraduate.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I&apos;m a hardworking, dedicated and reliable Software Engineering Undergraduate with strong problem solving and project management skills, 
            I am interested in the fields of Full Stack Web Development and Machine Learning. 
            A team man with leadership, analytic and presentation skills combined with a strong work ethic. 
            I am looking for a challenging career opportunity that will help me enhance my abilities and serve in the IT industry.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.instagram.com/_vindiya_/"><AiFillInstagram /></a>
              <a href="https://www.linkedin.com/in/vindiya-wickramathunga-6b6429221/"><AiFillLinkedin /></a>
              <a href="https://github.com/VindiyaRuchith"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profile} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I have a keen interest in full-stack web development. i have a solid foundation in technologies such as 
              HTML, CSS, ReactJS, TailwindCSS, PHP and MySQL, which enables me to develop and maintain dynamic and 
              responsive web applications. I also find the concept of machine learning intriguing and have a basic 
              understanding of Python and R, which i believe can be used to develop intelligent systems that can make better decisions
              and predictions. I am passionate about creating innovative and user-friendly applications while utilizing the latest
              technologies and techniques in the field of web development.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Mentioned below are some of the projects that i have created and contributed towards.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-cyan-500 flex-1">
              <Image src={dietyou} width={800} height={400}  />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                DietYou
              </h3>
              <p className="py-2">
              DietYou is a PHP web application that works as a diet planner to help users reduce NCDS by managing their weight and controlling their health. 
              The application takes user details such as weight, height, preferences, and diseases to create an accurate diet plan for a healthier life.(Group Project)
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  bg-cyan-500 flex-1">
              <Image src={portfolio} width={800} height={400}  />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Personal Portfolio
              </h3>
              <p className="py-2">
                A personal portfolio website created using ReactJS and Tailwind CSS to showcase skill&apos;s, projects and profile information.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  bg-cyan-500 flex-1">
              <Image src={empire} width={800} height={400} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Entertainment Empire</h3>
              <p className="py-2">
                A movie website created using ReactJS, where user can enter the movie they are searching for and it will be visible.
              </p>
            </div>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10   bg-cyan-500 flex-1">
              <Image src={mavs} width={800} height={400} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                MAVS Football
              </h3>
              <p className="py-2">
              A front-end sports website centered around football where users are able view information about the sport, buy merch,
              take part in a quiz,etc..(Group project).
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  bg-cyan-500 flex-1">
              
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Template
              </h3>
              <p className="py-2">
                
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  bg-cyan-500 flex-1">
              
              <h3 className="text-lg font-medium pt-8 pb-2 ">Template</h3>
              <p className="py-2">
 
              </p>
            </div>
            
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-center text-3xl py-1 dark:text-white ">Portfolio Gallery</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={diet1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50"}
                layout="responsive"
                src={diet2}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={mav1}
                alt = "mav snap"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={mav2}
                alt = "mavs snap"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={emp1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={emp2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={per1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={portfolio}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
